#nullable enable

using System;

namespace GenexusOpenApiBuilder.Extension.Domain;

internal static class ExtensionOutputLocalization
{
    private sealed class Phrase
    {
        public Phrase(string source, string spanish, string english)
        {
            Source = source;
            Spanish = spanish;
            English = english;
        }

        public string Source { get; }

        public string Spanish { get; }

        public string English { get; }
    }

    private static readonly Phrase[] Phrases =
    {
        new("API gerada com avisos.", "API generada con advertencias.", "API generated with warnings."),
        new("Relatório final:", "Informe final:", "Final report:"),
        new("Relatorio final:", "Informe final:", "Final report:"),
        new("Operação='", "Operación='", "Operation='"),
        new("Resultado='", "Resultado='", "Outcome='"),
        new("Criados=", "Creados=", "Created="),
        new("Atualizados=", "Actualizados=", "Updated="),
        new("Removidos=", "Eliminados=", "Removed="),
        new("Bloqueados=", "Bloqueados=", "Blocked="),
        new("Avisos=", "Advertencias=", "Warnings="),
        new("DuraçãoMs=", "DuraciónMs=", "DurationMs="),
        new("Título='", "Título='", "Headline='"),
        new("Operação:", "Operación:", "Operation:"),
        new("Operation='", "Operación='", "Operation='"),
        new("Outcome='", "Resultado='", "Outcome='"),
        new("Created=", "Creados=", "Created="),
        new("Updated=", "Actualizados=", "Updated="),
        new("Deleted=", "Eliminados=", "Deleted="),
        new("Blocked=", "Bloqueados=", "Blocked="),
        new("Warnings=", "Advertencias=", "Warnings="),
        new("DurationMs=", "DuraciónMs=", "DurationMs="),
        new("Headline='", "Titular='", "Headline='"),
        new("Tempo:", "Tiempo:", "Time:"),
        new("Criados:", "Creados:", "Created:"),
        new("Criados (", "Creados (", "Created ("),
        new("Atualizados:", "Actualizados:", "Updated:"),
        new("Atualizados (", "Actualizados (", "Updated ("),
        new("Removidos:", "Eliminados:", "Removed:"),
        new("Removidos (", "Eliminados (", "Removed ("),
        new("Bloqueados:", "Bloqueados:", "Blocked:"),
        new("Bloqueados (", "Bloqueados (", "Blocked ("),
        new("Avisos:", "Advertencias:", "Warnings:"),
        new("Avisos (", "Advertencias (", "Warnings ("),
        new("(nenhum)", "(ninguno)", "(none)"),
        new("(nenhuma)", "(ninguna)", "(none)"),
        new("com sucesso.", "con éxito.", "successfully."),
        new("com avisos.", "con advertencias.", "with warnings."),
        new("Remocao interrompida.", "Eliminación interrumpida.", "Removal interrupted."),
        new("Remoção interrompida.", "Eliminación interrumpida.", "Removal interrupted."),
        new("Sincronizacao interrompida.", "Sincronización interrumpida.", "Synchronization interrupted."),
        new("Sincronização interrompida.", "Sincronización interrumpida.", "Synchronization interrupted."),
        new("Geracao interrompida.", "Generación interrumpida.", "Generation interrupted."),
        new("Geração interrompida.", "Generación interrumpida.", "Generation interrupted."),
        new("Nenhuma Knowledge Base ativa foi encontrada.", "No se encontró ninguna Knowledge Base activa.", "No active Knowledge Base was found."),
        new("Abra uma KB e execute o comando novamente.", "Abra una KB y ejecute el comando nuevamente.", "Open a KB and run the command again."),
        new("Nenhuma alteração foi feita na KB.", "No se realizaron cambios en la KB.", "No changes were made to the KB."),
        new("Nenhuma alteracao foi feita na KB.", "No se realizaron cambios en la KB.", "No changes were made to the KB."),
        new("Configuração de preferências do wizard cancelada.", "Se canceló la configuración de preferencias del wizard.", "Wizard preference configuration was canceled."),
        new("Configuracao de preferencias do wizard cancelada.", "Se canceló la configuración de preferencias del wizard.", "Wizard preference configuration was canceled."),
        new("Preferências do wizard gravadas na KB ativa:", "Preferencias del wizard guardadas en la KB activa:", "Wizard preferences saved to the active KB:"),
        new("Preferencias do wizard gravadas na KB ativa:", "Preferencias del wizard guardadas en la KB activa:", "Wizard preferences saved to the active KB:"),
        new("O próximo wizard aplicará esses defaults quando a etapa estiver habilitada pelo estado da KB.", "El próximo wizard aplicará estos valores predeterminados cuando la etapa esté habilitada por el estado de la KB.", "The next wizard will apply these defaults when the stage is enabled by the KB state."),
        new("O proximo wizard aplicara esses defaults quando a etapa estiver habilitada pelo estado da KB.", "El próximo wizard aplicará estos valores predeterminados cuando la etapa esté habilitada por el estado de la KB.", "The next wizard will apply these defaults when the stage is enabled by the KB state."),
        new("Gravação de preferências bloqueada ou falhou antes de concluir:", "El guardado de preferencias fue bloqueado o falló antes de finalizar:", "Saving preferences was blocked or failed before completion:"),
        new("Gravacao de preferencias bloqueada ou falhou antes de concluir:", "El guardado de preferencias fue bloqueado o falló antes de finalizar:", "Saving preferences was blocked or failed before completion:"),
        new("Nenhuma Transaction elegível foi encontrada na Knowledge Base ativa.", "No se encontró ninguna Transaction elegible en la Knowledge Base activa.", "No eligible Transaction was found in the active Knowledge Base."),
        new("Transactions elegíveis encontradas:", "Transactions elegibles encontradas:", "Eligible Transactions found:"),
        new("Transaction elegível:", "Transaction elegible:", "Eligible Transaction:"),
        new("O diálogo público de seleção não está disponível nesta IDE.", "El diálogo público de selección no está disponible en esta IDE.", "The public selection dialog is not available in this IDE."),
        new("Nenhuma Transaction foi selecionada.", "No se seleccionó ninguna Transaction.", "No Transaction was selected."),
        new("A seleção retornada não é uma Transaction.", "La selección devuelta no es una Transaction.", "The returned selection is not a Transaction."),
        new("Nenhuma escolha foi mantida.", "No se conservó ninguna selección.", "No selection was kept."),
        new("A Transaction selecionada não possui módulo disponível:", "La Transaction seleccionada no tiene un módulo disponible:", "The selected Transaction has no available module:"),
        new("Transaction selecionada:", "Transaction seleccionada:", "Selected Transaction:"),
        new("Módulo da Transaction:", "Módulo de la Transaction:", "Transaction module:"),
        new("Nenhuma Transaction selecionada em memória.", "No se seleccionó ninguna Transaction en memoria.", "No Transaction is selected in memory."),
        new("Nenhuma Transaction selecionada em memoria.", "No se seleccionó ninguna Transaction en memoria.", "No Transaction is selected in memory."),
        new("Use o menu de contexto de uma Transaction ou execute primeiro o comando Abrir Wizard (B030).", "Use el menú contextual de una Transaction o ejecute primero el comando Abrir Wizard (B030).", "Use a Transaction context menu or run the Open Wizard command (B030) first."),
        new("Use o menu de contexto de uma Transaction ou execute primeiro o comando B022.", "Use el menú contextual de una Transaction o ejecute primero el comando B022.", "Use a Transaction context menu or run command B022 first."),
        new("Execute primeiro o comando Abrir Wizard (B030).", "Ejecute primero el comando Abrir Wizard (B030).", "Run the Open Wizard command (B030) first."),
        new("Execute primeiro o comando B022.", "Ejecute primero el comando B022.", "Run command B022 first."),
        new("A Transaction do menu de contexto não foi reencontrada na Knowledge Base ativa.", "La Transaction del menú contextual no fue reencontrada en la Knowledge Base activa.", "The context-menu Transaction was not found again in the active Knowledge Base."),
        new("A Transaction do menu de contexto nao foi reencontrada na Knowledge Base ativa.", "La Transaction del menú contextual no fue reencontrada en la Knowledge Base activa.", "The context-menu Transaction was not found again in the active Knowledge Base."),
        new("A Transaction selecionada não foi reencontrada na Knowledge Base ativa.", "La Transaction seleccionada no fue reencontrada en la Knowledge Base activa.", "The selected Transaction was not found again in the active Knowledge Base."),
        new("não foi reencontrada:", "no fue reencontrada:", "was not found again:"),
        new("Nao foi reencontrada:", "No fue reencontrada:", "Was not found again:"),
        new("Nenhuma escolha foi persistida.", "No se guardó ninguna selección.", "No selection was persisted."),
        new("Nenhum ApiPlan em memória foi encontrado.", "No se encontró ningún ApiPlan en memoria.", "No ApiPlan was found in memory."),
        new("Nenhum ApiPlan em memoria foi encontrado.", "No se encontró ningún ApiPlan en memoria.", "No ApiPlan was found in memory."),
        new("Execute e conclua primeiro o comando Abrir Wizard (B030).", "Ejecute y complete primero el comando Abrir Wizard (B030).", "Run and complete the Open Wizard command (B030) first."),
        new("Nenhuma Transaction selecionada em memoria foi encontrada.", "No se encontró ninguna Transaction seleccionada en memoria.", "No selected Transaction was found in memory."),
        new("ApiPlan em memória pertence a", "El ApiPlan en memoria pertenece a", "The ApiPlan in memory belongs to"),
        new("ApiPlan em memoria pertence a", "El ApiPlan en memoria pertenece a", "The ApiPlan in memory belongs to"),
        new("mas a seleção atual é", "pero la selección actual es", "but the current selection is"),
        new("mas a selecao atual e", "pero la selección actual es", "but the current selection is"),
        new("Execute novamente o wizard.", "Ejecute nuevamente el wizard.", "Run the wizard again."),
        new("Criacao de SDTs cancelada pelo usuario para", "Creación de SDTs cancelada por el usuario para", "SDT creation canceled by the user for"),
        new("Escrita de SDTs concluida:", "Escritura de SDTs completada:", "SDT writing completed:"),
        new("Nenhuma Procedure, API Object ou metadata persistente definitiva foi criada.", "No se creó ninguna Procedure, API Object ni metadata persistente definitiva.", "No Procedure, API Object, or definitive persistent metadata was created."),
        new("Criacao de SDTs bloqueada por preflight ou falhou antes de concluir:", "La creación de SDTs fue bloqueada por el preflight o falló antes de finalizar:", "SDT creation was blocked by preflight or failed before completion:"),
        new("Criacao de Procedures cancelada pelo usuario", "Creación de Procedures cancelada por el usuario", "Procedure creation canceled by the user"),
        new("Escrita de Procedures concluida:", "Escritura de Procedures completada:", "Procedure writing completed:"),
        new("Nenhum API Object, REST completo ou metadata persistente definitiva foi criado.", "No se creó ningún API Object, REST completo ni metadata persistente definitiva.", "No API Object, complete REST, or definitive persistent metadata was created."),
        new("Criacao de Procedures bloqueada por preflight ou falhou antes de concluir:", "La creación de Procedures fue bloqueada por el preflight o falló antes de finalizar:", "Procedure creation was blocked by preflight or failed before completion:"),
        new("Criacao de API Object cancelada pelo usuario", "Creación de API Object cancelada por el usuario", "API Object creation canceled by the user"),
        new("Escrita de API Object concluida:", "Escritura de API Object completada:", "API Object writing completed:"),
        new("Nenhum REST completo, seguranca definitiva ou metadata persistente definitiva foi criado.", "No se creó REST completo, seguridad definitiva ni metadata persistente definitiva.", "No complete REST, definitive security, or definitive persistent metadata was created."),
        new("Criacao de API Object bloqueada por preflight ou falhou antes de concluir:", "La creación de API Object fue bloqueada por el preflight o falló antes de finalizar:", "API Object creation was blocked by preflight or failed before completion:"),
        new("Descricoes aplicadas no API Object real:", "Descripciones aplicadas en el API Object real:", "Descriptions applied to the real API Object:"),
        new("Descricoes reaplicadas no API Object real durante B071-B073/B079:", "Descripciones reaplicadas en el API Object real durante B071-B073/B079:", "Descriptions reapplied to the real API Object during B071-B073/B079:"),
        new("Descricoes reaplicadas no API Object real", "Descripciones reaplicadas en el API Object real", "Descriptions reapplied to the real API Object"),
        new("Sem antecipar REST completo, codigo HTTP, seguranca definitiva ou metadata persistente.", "Sin anticipar REST completo, código HTTP, seguridad definitiva ni metadata persistente.", "Without anticipating complete REST, HTTP code, definitive security, or persistent metadata."),
        new("Metadata persistente inicial gravada:", "Metadata persistente inicial guardada:", "Initial persistent metadata saved:"),
        new("A metadata registra o snapshot do ApiPlan e dos artefatos ja aplicados; seguranca definitiva permanece fora desta etapa.", "La metadata registra la instantánea del ApiPlan y de los artefactos ya aplicados; la seguridad definitiva permanece fuera de esta etapa.", "The metadata records the ApiPlan and already-applied artifacts snapshot; definitive security remains outside this stage."),
        new("Alteracoes deliberadas pelo Wizard/Sincronizar atualizam esse baseline; alteracoes diretas nos objetos continuam bloqueadas antes de qualquer Save().", "Los cambios deliberados del Wizard/Sincronizar actualizan este baseline; los cambios directos en los objetos siguen bloqueados antes de cualquier Save().", "Intentional Wizard/Synchronize changes update this baseline; direct object changes remain blocked before any Save()."),
        new("Reexecucoes com descricoes, ownership, Service Source ou baseline divergente serao bloqueadas antes de qualquer Save().", "Las reejecuciones con descripciones, ownership, Service Source o baseline divergente se bloquearán antes de cualquier Save().", "Re-executions with divergent descriptions, ownership, Service Source, or baseline will be blocked before any Save()."),
        new("Get/Create/Update aplicados via Business Component e API Object sincronizado:", "Get/Create/Update aplicados mediante Business Component y API Object sincronizado:", "Get/Create/Update applied through Business Component and API Object synchronized:"),
        new("Aplicacao REST de Get/Create/Update bloqueada por preflight ou falhou antes de concluir:", "La aplicación REST de Get/Create/Update fue bloqueada por el preflight o falló antes de finalizar:", "Get/Create/Update REST application was blocked by preflight or failed before completion:"),
        new("List aplicado e API Object sincronizado:", "List aplicado y API Object sincronizado:", "List applied and API Object synchronized:"),
        new("Aplicacao do List bloqueada por preflight ou falhou antes de concluir:", "La aplicación de List fue bloqueada por el preflight o falló antes de finalizar:", "List application was blocked by preflight or failed before completion:"),
        new("B076 e validacao runtime do List permanecem pendentes.", "B076 y la validación runtime de List siguen pendientes.", "B076 and List runtime validation remain pending."),
        new("Conflitos de SDT:", "Conflictos de SDT:", "SDT conflicts:"),
        new("Diff para", "Diferencia para", "Diff for"),
        new("Nenhuma diferenca entre Transaction e metadata.", "No hay diferencias entre Transaction y metadata.", "There is no difference between Transaction and metadata."),
        new("Sincronizacao cancelada pelo usuario para", "Sincronización cancelada por el usuario para", "Synchronization canceled by the user for"),
        new("Sincronizacao bloqueada ou falhou:", "La sincronización fue bloqueada o falló:", "Synchronization was blocked or failed:"),
        new("Preflight de sincronizacao aprovado. Aplicando", "Preflight de sincronización aprobado. Aplicando", "Synchronization preflight approved. Applying"),
        new("Sincronizacao concluida para", "Sincronización completada para", "Synchronization completed for"),
        new("Plano de remocao para", "Plan de eliminación para", "Removal plan for"),
        new("Remocao cancelada pelo usuario para", "Eliminación cancelada por el usuario para", "Removal canceled by the user for"),
        new("Remocao concluida:", "Eliminación completada:", "Removal completed:"),
        new("SDTs compartilhados e Business Component da Transaction nao foram alterados.", "Los SDTs compartidos y el Business Component de la Transaction no fueron modificados.", "Shared SDTs and the Transaction Business Component were not changed."),
        new("Remocao bloqueada ou falhou:", "La eliminación fue bloqueada o falló:", "Removal was blocked or failed:"),
        new("Estado anterior do wizard descartado;", "Se descartó el estado anterior del wizard;", "Previous wizard state was discarded;"),
        new("Nenhuma etapa de escrita foi confirmada no wizard", "No se confirmó ninguna etapa de escritura en el wizard", "No writing stage was confirmed in the wizard"),
        new("Nenhuma escrita foi solicitada.", "No se solicitó ninguna escritura.", "No writing was requested."),
        new("Preflight agregado bloqueou o wizard antes do primeiro Save():", "El preflight agregado bloqueó el wizard antes del primer Save():", "Aggregated preflight blocked the wizard before the first Save():"),
        new("Preflight agregado aprovado antes do primeiro Save():", "Preflight agregado aprobado antes del primer Save():", "Aggregated preflight approved before the first Save():"),
        new("baseline da extensao ou objetos proprios ausentes, externos ou ambiguos em ", "baseline de la extensión u objetos propios ausentes, externos o ambiguos en ", "the extension baseline or owned objects missing, external, or ambiguous in "),
        new("Wizard concluído sem acionar cancelamento.", "Wizard completado sin activar la cancelación.", "Wizard completed without triggering cancellation."),
        new("Wizard concluido sem acionar cancelamento.", "Wizard completado sin activar la cancelación.", "Wizard completed without triggering cancellation."),
        new("Decisões e ApiPlan permanecem em memória.", "Las decisiones y el ApiPlan permanecen en memoria.", "Decisions and the ApiPlan remain in memory."),
        new("Decisoes e ApiPlan permanecem em memoria.", "Las decisiones y el ApiPlan permanecen en memoria.", "Decisions and the ApiPlan remain in memory."),
        new("Campos bloqueados visíveis no wizard:", "Campos bloqueados visibles en el wizard:", "Blocked fields visible in the wizard:"),
        new("Campos bloqueados visiveis no wizard:", "Campos bloqueados visibles en el wizard:", "Blocked fields visible in the wizard:"),
        new("Itens bloqueados ficaram desmarcados, com motivo, e não podem ser selecionados.", "Los elementos bloqueados quedaron desmarcados, con motivo, y no pueden seleccionarse.", "Blocked items remained unchecked with a reason and cannot be selected."),
        new("Itens bloqueados ficaram desmarcados, com motivo, e nao podem ser selecionados.", "Los elementos bloqueados quedaron desmarcados, con motivo, y no pueden seleccionarse.", "Blocked items remained unchecked with a reason and cannot be selected."),
        new("Campos sensíveis no plano:", "Campos sensibles en el plan:", "Sensitive fields in the plan:"),
        new("Campos sensiveis no plano:", "Campos sensibles en el plan:", "Sensitive fields in the plan:"),
        new("Folder '", "Folder '", "Folder '"),
        new("nao foi apagado porque nao ficou vazio.", "no se eliminó porque no quedó vacío.", "was not deleted because it was not empty."),
        new("não foi apagado porque não ficou vazio.", "no se eliminó porque no quedó vacío.", "was not deleted because it was not empty."),
        new("Business Component habilitado durante o Wizard", "Business Component habilitado durante el Wizard", "Business Component enabled during the Wizard"),
        new("Business Component habilitado durante o wizard", "Business Component habilitado durante el wizard", "Business Component enabled during the wizard"),
        new("Obrigatoriedade em memoria:", "Obligatoriedad en memoria:", "Required fields in memory:"),
        new("Obrigatoriedade em memória:", "Obligatoriedad en memoria:", "Required fields in memory:"),
        new("Required marca membro obrigatorio no payload, recusado com 400 quando ausente ou com o valor default do tipo (vazio, false ou 0).", "Required marca el miembro como obligatorio en el payload; se rechaza con 400 cuando falta o tiene el valor predeterminado del tipo (vacío, false o 0).", "Required marks a member as mandatory in the payload; it is rejected with 400 when missing or set to the type default value (empty, false, or 0)."),
        new("Required marca membro obrigatório no payload, recusado com 400 quando ausente ou com o valor default do tipo (vazio, false ou 0).", "Required marca el miembro como obligatorio en el payload; se rechaza con 400 cuando falta o tiene el valor predeterminado del tipo (vacío, false o 0).", "Required marks a member as mandatory in the payload; it is rejected with 400 when missing or set to the type default value (empty, false, or 0)."),
        new("Obrigatorio no payload consolidado:", "Obligatorio en el payload consolidado:", "Required in the consolidated payload:"),
        new("Obrigatório no payload consolidado:", "Obligatorio en el payload consolidado:", "Required in the consolidated payload:"),
        new("Create/Update respondem 400 quando o obrigatorio chega ausente ou com o valor default do tipo; o GeneXus nao expoe presenca de membro JSON sem comando csharp. UpdateRequest segue PUT completo.", "Create/Update responden 400 cuando el obligatorio llega ausente o con el valor predeterminado del tipo; GeneXus no expone la presencia de un miembro JSON sin un comando de C#. UpdateRequest sigue PUT completo.", "Create/Update return 400 when the required member is missing or has the type default value; GeneXus does not expose JSON member presence without a C# command. UpdateRequest follows a full PUT."),
        new("Create/Update respondem 400 quando o obrigatório chega ausente ou com o valor default do tipo; o GeneXus não expõe presença de membro JSON sem comando csharp. UpdateRequest segue PUT completo.", "Create/Update responden 400 cuando el obligatorio llega ausente o con el valor predeterminado del tipo; GeneXus no expone la presencia de un miembro JSON sin un comando de C#. UpdateRequest sigue PUT completo.", "Create/Update return 400 when the required member is missing or has the type default value; GeneXus does not expose JSON member presence without a C# command. UpdateRequest follows a full PUT."),
        new("Wizard único concluido em memoria:", "Asistente único completado en memoria:", "Single wizard completed in memory:"),
        new("Wizard único concluído em memória:", "Asistente único completado en memoria:", "Single wizard completed in memory:"),
        new("Contrato de API da Transacao=", "Contrato de API de la Transaction=", "Transaction API contract="),
        new("Contrato de API da Transação=", "Contrato de API de la Transaction=", "Transaction API contract="),
        new("ApiPlan cobre:", "El ApiPlan cubre:", "ApiPlan covers:"),
        new("Paths, segurança e paginacao em memoria:", "Paths, seguridad y paginación en memoria:", "Paths, security, and pagination in memory:"),
        new("Paths, segurança e paginação em memória:", "Paths, seguridad y paginación en memoria:", "Paths, security, and pagination in memory:"),
        new("Paginacao e ordenacao:", "Paginación y ordenación:", "Pagination and ordering:"),
        new("Paginacao e ordenação:", "Paginación y ordenación:", "Pagination and ordering:"),
        new("Classificacao em memoria:", "Clasificación en memoria:", "Classification in memory:"),
        new("Classificação em memória:", "Clasificación en memoria:", "Classification in memory:"),
        new("Metadata futura no ApiPlan:", "Metadata futura en el ApiPlan:", "Future metadata in the ApiPlan:"),
        new("Seguranca no ApiPlan:", "Seguridad en el ApiPlan:", "Security in the ApiPlan:"),
        new("Segurança no ApiPlan:", "Seguridad en el ApiPlan:", "Security in the ApiPlan:"),
        new("Preview de engine SDT:", "Vista previa del motor SDT:", "SDT engine preview:"),
        new("Campos de engine no ApiPlan:", "Campos del motor en el ApiPlan:", "Engine fields in the ApiPlan:"),
        new("Descricoes no ApiPlan:", "Descripciones en el ApiPlan:", "Descriptions in the ApiPlan:"),
        new("Descrições no ApiPlan:", "Descripciones en el ApiPlan:", "Descriptions in the ApiPlan:"),
        new("Sem persistir metadata e sem gerar SDT, Procedure, API Object ou File na KB.", "Sin persistir metadata ni generar SDT, Procedure, API Object o File en la KB.", "Without persisting metadata or generating an SDT, Procedure, API Object, or File in the KB."),
        new("Sem aplicar [Description] em objeto API real e sem gerar objetos.", "Sin aplicar [Description] en el API Object real ni generar objetos.", "Without applying [Description] to the real API Object or generating objects."),
        new("Sem aplicar seguranca em objetos reais.", "Sin aplicar seguridad en objetos reales.", "Without applying security to real objects."),
        new("Sem aplicar segurança em objetos reais.", "Sin aplicar seguridad en objetos reales.", "Without applying security to real objects."),
        new("Sem validar engine real e sem gerar objetos.", "Sin validar el motor real ni generar objetos.", "Without validating the real engine or generating objects."),
        new("Sem criar, alterar ou excluir objetos na KB.", "Sin crear, alterar ni eliminar objetos en la KB.", "Without creating, changing, or deleting objects in the KB."),
        new("Proximo passo habilitado para", "Siguiente paso habilitado para", "Next step enabled for"),
        new("Próximo passo habilitado para", "Siguiente paso habilitado para", "Next step enabled for"),
        new("Nenhum Save foi solicitado.", "No se solicitó ningún Save.", "No Save was requested."),
        new("Nenhuma etapa de escrita foi confirmada no wizard", "No se confirmó ninguna etapa de escritura en el asistente", "No writing stage was confirmed in the wizard"),
        new("Nenhuma escrita foi solicitada.", "No se solicitó ninguna escritura.", "No writing was requested."),
        new("A dependencia sera reencontrada e validada pelo preflight da etapa seguinte.", "La dependencia se reencontrará y validará mediante el preflight de la siguiente etapa.", "The dependency will be found again and validated by the next stage preflight."),
        new("A dependência será reencontrada e validada pelo preflight da etapa seguinte.", "La dependencia se reencontrará y validará mediante el preflight de la siguiente etapa.", "The dependency will be found again and validated by the next stage preflight."),
        new("Etapa de", "Etapa de", "Stage of"),
        new("nao foi aplicado para", "no se aplicó para", "was not applied for"),
        new("não foi aplicado para", "no se aplicó para", "was not applied for"),
        new("nao foi gravada para", "no se guardó para", "was not saved for"),
        new("não foi gravada para", "no se guardó para", "was not saved for"),
        new("porque", "porque", "because"),
        new("falhou ou foi bloqueado neste fluxo.", "falló o fue bloqueado en este flujo.", "failed or was blocked in this flow."),
        new("falhou ou foi bloqueada neste fluxo.", "falló o fue bloqueada en este flujo.", "failed or was blocked in this flow."),
        new("Como B071-B073/B079 tambem foi confirmado, a atualizacao do API Object sera absorvida pelo preflight de Business Component.", "Como B071-B073/B079 también fue confirmado, la actualización del API Object será absorbida por el preflight de Business Component.", "As B071-B073/B079 was also confirmed, the API Object update will be handled by the Business Component preflight."),
        new("tambem foi confirmado", "también fue confirmado", "was also confirmed"),
        new("tambem fue confirmado", "también fue confirmado", "was also confirmed"),
        new("foi confirmado", "fue confirmado", "was confirmed"),
        new("foi bloqueado", "fue bloqueado", "was blocked"),
        new("foi bloqueada", "fue bloqueada", "was blocked"),
        new("ja existe para", "ya existe para", "already exists for"),
        new("já existe para", "ya existe para", "already exists for"),
        new("A atualizacao do API Object sera absorvida pelo preflight de Business Component.", "La actualización del API Object será absorbida por el preflight de Business Component.", "The API Object update will be handled by the Business Component preflight."),
        new("A atualização do API Object será absorvida pelo preflight de Business Component.", "La actualización del API Object será absorbida por el preflight de Business Component.", "The API Object update will be handled by the Business Component preflight."),
        new("Nível de segurança", "Nivel de seguridad", "Security level"),
        new("Adicionados:", "Agregados:", "Added:"),
        new("Removidos:", "Eliminados:", "Removed:"),
        new("Renomeados:", "Renombrados:", "Renamed:"),
        new("Modificados:", "Modificados:", "Modified:"),
        new("Inalterados:", "Sin cambios:", "Unchanged:"),
        new("tipo ", "tipo ", "type "),
        new("natureza estrutural (formula/inferido/redundante) alterada", "naturaleza estructural (fórmula/inferido/redundante) modificada", "structural nature (formula/inferred/redundant) changed"),
        new("natureza estrutural (fórmula/inferido/redundante) alterada", "naturaleza estructural (fórmula/inferido/redundante) modificada", "structural nature (formula/inferred/redundant) changed"),
        new("API Object:", "API Object:", "API Object:"),
        new("Metadata File:", "Archivo de metadata:", "Metadata File:"),
        new("Procedures (", "Procedures (", "Procedures ("),
        new("SDTs próprios (", "SDTs propios (", "Own SDTs ("),
        new("SDTs próprios", "SDTs propios", "Own SDTs"),
        new("SDTs compartilhados preservados (", "SDTs compartidos preservados (", "Preserved shared SDTs ("),
        new("SDTs compartilhados preservados", "SDTs compartidos preservados", "Preserved shared SDTs"),
        new("criado pela extensão; apagar só se ficar vazio", "creado por la extensión; eliminar solo si queda vacío", "created by the extension; delete only if it remains empty"),
        new("reutilizado; nunca apagar", "reutilizado; nunca eliminar", "reused; never delete"),
        new("Business Component da Transaction: não será revertido.", "Business Component de la Transaction: no será revertido.", "Transaction Business Component: it will not be reverted."),
        new("Business Component da Transaction: nao sera revertido.", "Business Component de la Transaction: no será revertido.", "Transaction Business Component: it will not be reverted."),
        new("Objeto principal", "Objeto principal", "Main object"),
        new("nao foi encontrado na KB.", "no se encontró en la KB.", "was not found in the KB."),
        new("não foi encontrado na KB.", "no se encontró en la KB.", "was not found in the KB."),
        new("Nao foi possivel abrir o objeto principal: ", "No fue posible abrir el objeto principal: ", "Could not open the main object: "),
        new("Não foi possível abrir o objeto principal: ", "No fue posible abrir el objeto principal: ", "Could not open the main object: "),
        new("Descricoes de servico usaram fallback em ingles", "Las descripciones de servicio usaron fallback en inglés", "Service descriptions used an English fallback"),
        new("Idioma principal da KB ainda nao validado por API publica", "El idioma principal de la KB aún no fue validado por una API pública", "The KB primary language has not yet been validated through a public API"),
        new("Atenção:", "Atención:", "Warning:"),
        new("Aviso:", "Advertencia:", "Warning:"),
        new("Criado:", "Creado:", "Created:"),
        new("Atualizado:", "Actualizado:", "Updated:"),
        new("Removido:", "Eliminado:", "Removed:"),
        new("Bloqueado:", "Bloqueado:", "Blocked:"),
        new("Causa principal: ", "Causa principal: ", "Primary cause: "),
        new("Causa='", "Causa='", "Cause='"),
        new("ApiObjectGuid='", "GUIDApiObject='", "APIObjectGuid='"),
        new("MetadataApiGuid='", "GUIDMetadata='", "MetadataApiGuid='"),
        new("API Object GUID atual: ", "GUID actual del API Object: ", "Current API Object GUID: "),
        new("GUID da metadata: ", "GUID de los metadatos: ", "Metadata GUID: "),
        new("Arquivo de metadata: ", "Archivo de metadatos: ", "Metadata file: "),
        new("Metadata lida como JSON: ", "Metadatos leídos como JSON: ", "Metadata read as JSON: "),
        new("Ownership da metadata: ", "Propiedad de los metadatos: ", "Metadata ownership: "),
        new("Integridade B067: ", "Integridad B067: ", "B067 integrity: "),
        new("Service Source, variáveis e Events: ", "Service Source, variables y Events: ", "Service Source, variables, and Events: "),
        new("Description fallback: ", "Fallback de Description: ", "Description fallback: "),
        new("não encontrada", "no encontrada", "not found"),
        new("encontrada e reconhecida", "encontrada y reconocida", "found and recognized"),
        new("encontrada, mas Description não reconhecida", "encontrada, pero Description no reconocida", "found, but Description not recognized"),
        new("não aplicável", "no aplicable", "not applicable"),
        new("compatível", "compatible", "compatible"),
        new("incompatível", "incompatible", "incompatible"),
        new("gerenciados", "gestionados", "managed"),
        new("ausentes=", "ausentes=", "missing="),
        new("planejados", "planificados", "planned"),
        new("A confirmacao continua obrigatoria antes de qualquer escrita.", "La confirmación sigue siendo obligatoria antes de cualquier escritura.", "Confirmation remains mandatory before any writing."),
        new("Reencontrar e validar", "Reencontrar y validar", "Re-encounter and validate"),
        new("Preferencias do wizard carregadas da KB ativa:", "Preferencias del wizard cargadas de la KB activa:", "Wizard preferences loaded from the active KB:"),
        new("Preferências do wizard carregadas da KB ativa:", "Preferencias del wizard cargadas de la KB activa:", "Wizard preferences loaded from the active KB:"),
        new("ApiPlan em memoria criado:", "ApiPlan en memoria creado:", "ApiPlan created in memory:"),
        new("ApiPlan em memória criado:", "ApiPlan en memoria creado:", "ApiPlan created in memory:"),
        new("SDT planejado:", "SDT planificado:", "Planned SDT:"),
        new("como gerador prioritario inicial do MVP", "como generador prioritario inicial del MVP", "as the MVP's initial priority generator"),
        new("para colisao externa/incompativel", "para colisión externa/incompatible", "for external/incompatible collision"),
        new("Contrato por KB preparado no ApiPlan, ainda sem metadata persistente e sem geracao.", "Contrato por KB preparado en el ApiPlan, aún sin metadatos persistentes y sin generación.", "KB contract prepared in the ApiPlan, still without persistent metadata and without generation."),
        new("Ainda sem ler ou gravar File de metadata.", "Aún sin leer ni grabar el File de metadatos.", "Still without reading or writing the metadata File."),
        new("Business Component em memoria:", "Business Component en memoria:", "Business Component in memory:"),
        new("Business Component em memória:", "Business Component en memoria:", "Business Component in memory:"),
        new("escritas confirmadas no wizard exigem preflight completo antes de qualquer Save().", "las escrituras confirmadas en el wizard exigen preflight completo antes de cualquier Save().", "writes confirmed in the wizard require a complete preflight before any Save()."),
        new("Metadata de integridade gravada:", "Metadata de integridad guardada:", "Integrity metadata saved:"),
        new("Status HTTP controlado por RestCode no API Object; ErrorResponse exposto como saida publica dos servicos; Location de Create emitido nativamente via HttpResponse.", "Status HTTP controlado por RestCode en el API Object; ErrorResponse expuesto como salida pública de los servicios; Location de Create emitido nativamente vía HttpResponse.", "HTTP status controlled by RestCode on the API Object; ErrorResponse exposed as a public service output; Create Location emitted natively via HttpResponse."),
        new("Service Source preserva o contrato Procedure/API Object atual.", "Service Source conserva el contrato Procedure/API Object actual.", "Service Source preserves the current Procedure/API Object contract."),
        new("idioma da KB ainda nao validado por API publica", "idioma de la KB aún no validado por API pública", "KB language not yet validated by a public API"),
        new("fallback tecnico em ingles registrado no ApiPlan", "fallback técnico en inglés registrado en el ApiPlan", "technical English fallback recorded in the ApiPlan"),
        new("Folder preexistente '", "Carpeta preexistente '", "Pre-existing folder '"),
        new("no contenedor correto sera reutilizado; a Description existente sera preservada e o Folder nunca sera removido pela remocao desta API.", "en el contenedor correcto será reutilizado; la Description existente se preservará y el Folder nunca será eliminado por la eliminación de esta API.", "in the correct container will be reused; the existing Description will be preserved and the Folder will never be removed by removing this API."),
        new("Apta via Business Component", "Apta mediante Business Component", "Ready via Business Component"),
        new("divergentes", "divergentes", "divergent"),
        new("Posse confirmada pela metadata.", "Propiedad confirmada por los metadatos.", "Ownership confirmed by metadata."),
        new("Posse confirmada pela Description fallback.", "Propiedad confirmada por el fallback de Description.", "Ownership confirmed by Description fallback."),
        new("Há mais de um arquivo de metadata com o mesmo nome.", "Hay más de un archivo de metadatos con el mismo nombre.", "More than one metadata file has the same name."),
        new("A Description do arquivo de metadata não é reconhecida como própria.", "La Description del archivo de metadatos no se reconoce como propia.", "The metadata file Description is not recognized as owned."),
        new("O arquivo de metadata próprio não pôde ser lido como JSON.", "No se pudo leer como JSON el archivo de metadatos propio.", "The owned metadata file could not be read as JSON."),
        new("O GUID atual do API Object diverge do GUID registrado na metadata.", "El GUID actual del API Object difiere del GUID registrado en los metadatos.", "The current API Object GUID differs from the GUID recorded in metadata."),
        new("O ownership registrado na metadata não corresponde ao API Object atual.", "La propiedad registrada en los metadatos no corresponde al API Object actual.", "The ownership recorded in metadata does not match the current API Object."),
        new("A integridade B067 da metadata não corresponde ao estado atual.", "La integridad B067 de los metadatos no corresponde al estado actual.", "The metadata B067 integrity does not match the current state."),
        new("Service Source, variáveis ou Events não correspondem ao contrato gerenciado.", "Service Source, variables o Events no corresponden al contrato gestionado.", "Service Source, variables, or Events do not match the managed contract."),
        new("A Description do API Object não corresponde a nenhum fallback próprio.", "La Description del API Object no corresponde a ningún fallback propio.", "The API Object Description does not match any owned fallback."),
        new("Nenhuma sincronizacao necessaria.", "Ninguna sincronización necesaria.", "No synchronization is necessary."),
        new("Nenhuma sincronização necessária.", "Ninguna sincronización necesaria.", "No synchronization is necessary."),
        new("a atualizacao do API Object sera absorvida pelo preflight de Business Component.", "la actualización del API Object será absorbida por el preflight de Business Component.", "the API Object update will be handled by the Business Component preflight."),
        new("a atualização do API Object será absorvida pelo preflight de Business Component.", "la actualización del API Object será absorbida por el preflight de Business Component.", "the API Object update will be handled by the Business Component preflight."),
        new(" em memoria:", " en memoria:", " in memory:"),
        new(" em memória:", " en memoria:", " in memory:"),
        new("colisao(oes) externa(s), incompativel(is), ambigua(s) ou integridade B067 divergente", "colisión(es) externa(s), incompatible(s), ambigua(s) o integridad B067 divergente", "external, incompatible, ambiguous collision(s), or divergent B067 integrity"),
        new("colisao(oes) externa(s), incompativel(is) ou ambigua(s)", "colisión(es) externa(s), incompatible(s) o ambigua(s)", "external, incompatible, or ambiguous collision(s)"),
        new("detectada(s).", "detectada(s).", "detected."),
        new("Nenhuma escrita sera permitida.", "No se permitirá ninguna escritura.", "No writing will be allowed."),
        new("Nenhuma escrita será permitida.", "No se permitirá ninguna escritura.", "No writing will be allowed."),
        new("Etapa '", "Etapa '", "Stage '"),
        new(" bloqueada na KB:", " bloqueada en la KB:", " blocked in the KB:"),
        new("Conflitos (", "Conflictos (", "Conflicts ("),
        new("Nome='", "Nombre='", "Name='"),
        new("Tipo='", "Tipo='", "Type='"),
        new("Modulo='", "Módulo='", "Module='"),
        new("o API Object precisa estar disponivel antes.", "el API Object debe estar disponible antes.", "the API Object must be available first."),
        new("o estado dos SDTs precisa ser resolvido antes.", "el estado de los SDTs debe resolverse antes.", "the SDT state must be resolved first."),
        new("o estado dos SDTs ou Procedures precisa ser resolvido antes.", "el estado de los SDTs o Procedures debe resolverse antes.", "the SDT or Procedure state must be resolved first."),
        new("Diagnostico de posse do API Object (baseline de alteracao intencional):", "Diagnóstico de propiedad del API Object (baseline de cambio intencional):", "API Object ownership diagnostic (intentional-change baseline):"),
        new("Diagnostico de posse do API Object:", "Diagnóstico de propiedad del API Object:", "API Object ownership diagnostic:"),
        new("etapa bloqueada sem lista de conflito.", "etapa bloqueada sin lista de conflicto.", "stage blocked without a conflict list."),
        new("ClausulaQueFalhou=", "ClausulaQueFallo=", "FailingClause="),
        new("MetadataPresente=", "MetadataPresente=", "MetadataPresent="),
        new("MetadataDescriptionPropria=", "MetadataDescriptionPropia=", "MetadataDescriptionOwned="),
        new("IntegrityPresente=", "IntegrityPresente=", "IntegrityPresent="),
        new("FingerprintPresente=", "FingerprintPresente=", "FingerprintPresent="),
        new("FingerprintAlgoritmoOk=", "FingerprintAlgoritmoOk=", "FingerprintAlgorithmOk="),
        new("FingerprintEscopoOk=", "FingerprintEscopoOk=", "FingerprintScopeOk="),
        new("FingerprintValorPresente=", "FingerprintValorPresente=", "FingerprintValuePresent="),
        new("FingerprintHashOk=", "FingerprintHashOk=", "FingerprintHashOk="),
        new("FingerprintDetalhe=", "FingerprintDetalle=", "FingerprintDetail="),
        new("FingerprintAlgoritmo=", "FingerprintAlgoritmo=", "FingerprintAlgorithm="),
        new("FingerprintEscopo=", "FingerprintEscopo=", "FingerprintScope="),
        new("FingerprintGravado=", "FingerprintGrabado=", "FingerprintStored="),
        new("FingerprintRecalculado=", "FingerprintRecalculado=", "FingerprintActual="),
        new("SchemaGravado=", "SchemaGrabado=", "StoredSchema="),
        new("ApiNameGravado=", "ApiNameGrabado=", "StoredApiName="),
        new("ApiNameEsperado=", "ApiNameEsperado=", "ExpectedApiName="),
        new("DescriptionAtual=", "DescriptionActual=", "CurrentDescription="),
        new("DescriptionSentinel=", "DescriptionSentinel=", "DescriptionSentinel="),
        new("ServiceSourceHashAtual=", "ServiceSourceHashActual=", "CurrentServiceSourceHash="),
        new("ServiceSourceHashGravado=", "ServiceSourceHashGrabado=", "StoredServiceSourceHash="),
        new("DescriptionsHashAtual=", "DescriptionsHashActual=", "CurrentDescriptionsHash="),
        new("DescriptionsHashGravado=", "DescriptionsHashGrabado=", "StoredDescriptionsHash="),
        new("Nenhum ApiPlan foi criado, nenhuma escolha foi persistida e nenhum objeto foi criado, alterado ou excluido.", "No se creó ningún ApiPlan, no se persistió ninguna elección y no se creó, alteró ni eliminó ningún objeto.", "No ApiPlan was created, no selection was persisted, and no object was created, changed, or deleted."),
        new("nenhum ApiPlan foi criado e nenhuma alteracao foi feita na KB.", "no se creó ningún ApiPlan y no se realizaron cambios en la KB.", "no ApiPlan was created and no changes were made to the KB."),
        new("Nenhum ApiPlan foi criado e nenhuma alteracao foi feita na KB.", "No se creó ningún ApiPlan y no se realizaron cambios en la KB.", "No ApiPlan was created and no changes were made to the KB."),
        new("nenhum ApiPlan foi criado.", "no se creó ningún ApiPlan.", "no ApiPlan was created."),
        new("Nenhum ApiPlan foi criado.", "No se creó ningún ApiPlan.", "No ApiPlan was created."),
        new("Voltar acionado no início do wizard único.", "Se activó Atrás al inicio del asistente único.", "Back was used at the start of the single wizard."),
        new("Voltar acionado durante o fluxo B032.", "Se activó Atrás durante el flujo B032.", "Back was used during the B032 flow."),
        new("Voltar acionado no Passo 3.", "Se activó Atrás en el Paso 3.", "Back was used on Step 3."),
        new("Voltar acionado no Passo 2.", "Se activó Atrás en el Paso 2.", "Back was used on Step 2."),
        new("e decisões em memoria foram descartadas;", "y las decisiones en memoria se descartaron;", "and in-memory decisions were discarded;"),
        new("e decisões em memória foram descartadas;", "y las decisiones en memoria se descartaron;", "and in-memory decisions were discarded;"),
        new("Transaction e decisões em memoria descartadas;", "Transaction y decisiones en memoria descartadas;", "Transaction and in-memory decisions discarded;"),
        new("Transaction e decisões em memória descartadas;", "Transaction y decisiones en memoria descartadas;", "Transaction and in-memory decisions discarded;"),
        new("Wizard único cancelado ou fechado para", "Asistente único cancelado o cerrado para", "Single wizard canceled or closed for"),
        new("Wizard único fechado sem conclusao para", "Asistente único cerrado sin concluir para", "Single wizard closed without completion for"),
        new("Wizard único fechado sem conclusão para", "Asistente único cerrado sin concluir para", "Single wizard closed without completion for"),
        new("Estado em memoria descartado;", "Estado en memoria descartado;", "In-memory state discarded;"),
        new("Estado em memória descartado;", "Estado en memoria descartado;", "In-memory state discarded;"),
        new("Estado do wizard descartado;", "Estado del wizard descartado;", "Wizard state discarded;"),
        new("Business Component foi habilitado por confirmacao explicita antes da saida; essa alteracao foi gravada na KB e nao foi revertida automaticamente.", "El Business Component fue habilitado por confirmación explícita antes de salir; ese cambio se grabó en la KB y no se revirtió automáticamente.", "Business Component was enabled by explicit confirmation before exit; that change was saved to the KB and was not reverted automatically."),
        new("permaneceu selecionada em memoria;", "permaneció seleccionada en memoria;", "remained selected in memory;"),
        new("permaneceu selecionada em memória;", "permaneció seleccionada en memoria;", "remained selected in memory;"),
        new("nenhuma escolha de contrato foi persistida.", "no se persistió ninguna elección de contrato.", "no contract selection was persisted."),
        new("Wizard cancelado durante o fluxo B032 para", "Wizard cancelado durante el flujo B032 para", "Wizard canceled during the B032 flow for"),
        new("Wizard cancelado no Passo 3 para", "Wizard cancelado en el Paso 3 para", "Wizard canceled on Step 3 for"),
        new("Wizard cancelado no Passo 2 para", "Wizard cancelado en el Paso 2 para", "Wizard canceled on Step 2 for"),
        new("Escolhas em memoria descartadas;", "Selecciones en memoria descartadas;", "In-memory selections discarded;"),
        new("Escolhas em memória descartadas;", "Selecciones en memoria descartadas;", "In-memory selections discarded;"),
        new("Passo 2 fechado sem conclusao durante o fluxo B032 para", "Paso 2 cerrado sin concluir durante el flujo B032 para", "Step 2 closed without completion during the B032 flow for"),
        new("Passo 2 fechado sem conclusao para", "Paso 2 cerrado sin concluir para", "Step 2 closed without completion for"),
        new("Passo 2 fechado sem conclusão para", "Paso 2 cerrado sin concluir para", "Step 2 closed without completion for"),
        new("Passo 3 fechado sem conclusao para", "Paso 3 cerrado sin concluir para", "Step 3 closed without completion for"),
        new("Passo 3 fechado sem conclusão para", "Paso 3 cerrado sin concluir para", "Step 3 closed without completion for"),
        new("Wizard Passo 2 concluido em memoria durante o fluxo B032:", "Wizard Paso 2 completado en memoria durante el flujo B032:", "Wizard Step 2 completed in memory during the B032 flow:"),
        new("Wizard Passo 2 concluido em memoria:", "Wizard Paso 2 completado en memoria:", "Wizard Step 2 completed in memory:"),
        new("Wizard Passo 3 concluido em memoria:", "Wizard Paso 3 completado en memoria:", "Wizard Step 3 completed in memory:"),
        new("Reabrindo B031 para", "Reabriendo B031 para", "Reopening B031 for"),
        new("sem persistir escolhas.", "sin persistir selecciones.", "without persisting selections."),
        new("A Transaction selecionada nao possui modulo disponivel:", "La Transaction seleccionada no tiene un módulo disponible:", "The selected Transaction has no available module:"),
        new("Transaction resolvida para o wizard:", "Transaction resuelta para el wizard:", "Transaction resolved for the wizard:"),
        new("Contrato B031 ausente ou incompativel para", "Contrato B031 ausente o incompatible para", "B031 contract missing or incompatible for"),
        new("Contrato B031 ausente para", "Contrato B031 ausente para", "B031 contract missing for"),
        new("Abrindo B031 automaticamente.", "Abriendo B031 automáticamente.", "Opening B031 automatically."),
        new("Campos selecionados:", "Campos seleccionados:", "Selected fields:"),
        new("nenhuma escolha foi persistida.", "no se persistió ninguna selección.", "no selection was persisted."),
        new("nenhuma escolha foi mantida.", "no se conservó ninguna selección.", "no selection was kept."),
        new("nenhuma alteracao foi feita na KB.", "no se realizaron cambios en la KB.", "no changes were made to the KB."),
        new("bloqueada: Business Component desabilitado e habilitacao explicita nao confirmada.", "bloqueada: Business Component deshabilitado y habilitación explícita no confirmada.", "blocked: Business Component disabled and explicit enablement not confirmed."),
        new("Habilitacao de Business Component cancelada para", "Habilitación de Business Component cancelada para", "Business Component enablement canceled for"),
        new("Falha ao confirmar Business Component habilitado para", "Fallo al confirmar Business Component habilitado para", "Failed to confirm Business Component enabled for"),
        new("apos gravacao.", "después de la grabación.", "after saving."),
        new("Falha ao habilitar Business Component para", "Fallo al habilitar Business Component para", "Failed to enable Business Component for"),
        new("Business Component habilitado por confirmacao explicita para", "Business Component habilitado por confirmación explícita para", "Business Component enabled by explicit confirmation for"),
        new("A alteracao foi gravada na KB e nao sera revertida automaticamente.", "El cambio se grabó en la KB y no se revertirá automáticamente.", "The change was saved to the KB and will not be reverted automatically."),
        new("Nenhum", "Ningún", "No"),
    };

    public static string Translate(string message, ExtensionLanguage language)
    {
        if (string.IsNullOrEmpty(message) || language == ExtensionLanguage.PortugueseBrazil)
        {
            return message;
        }

        var localized = message;
        foreach (var phrase in Phrases)
        {
            localized = localized.Replace(
                phrase.Source,
                language == ExtensionLanguage.Spanish ? phrase.Spanish : phrase.English);
        }

        return localized;
    }
}
