<Project Sdk="GeneXus.Package.UI.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <PackageId>GenexusOpenApiBuilder.Extension</PackageId>
    <Version>0.1.0-preview.1</Version>
    <Authors>Genexus Open API Builder contributors</Authors>
    <Company>GxBrasilNOficial</Company>
    <Description>Genexus Open API Builder - Preview</Description>
    <AssemblyTitle>Genexus Open API Builder - Preview</AssemblyTitle>
    <Product>Genexus Open API Builder - Preview</Product>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0-preview.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AssemblyName>GenexusOpenApiBuilder.Extension</AssemblyName>
    <RootNamespace>GenexusOpenApiBuilder.Extension</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableSourceLink>false</EnableSourceLink>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
