Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$helperPath = Join-Path $PSScriptRoot '..\..\Src\Extension\Diagnostics\ApiPlanApiObjectOwnership.cs'
$newtonsoftPath = Get-ChildItem -Path (Join-Path $env:USERPROFILE '.nuget\packages\newtonsoft.json') -Filter Newtonsoft.Json.dll -Recurse |
    Where-Object { $_.FullName -match '\\lib\\netstandard2\.0\\Newtonsoft\.Json\.dll$' } |
    Sort-Object FullName -Descending |
    Select-Object -First 1 -ExpandProperty FullName

if ([string]::IsNullOrWhiteSpace($newtonsoftPath)) {
    throw 'Newtonsoft.Json.dll não encontrado no cache NuGet local.'
}

$runtimeAssemblies = @([System.AppContext]::GetData('TRUSTED_PLATFORM_ASSEMBLIES') -split [System.IO.Path]::PathSeparator |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
if ($runtimeAssemblies.Count -eq 0) {
    throw 'Assemblies do runtime PowerShell atual não foram encontrados.'
}

Add-Type -Path $helperPath -ReferencedAssemblies @(($runtimeAssemblies + $newtonsoftPath) | Sort-Object -Unique)

function Assert-True {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) {
        throw "ASSERT_TRUE_FAILED: $Message"
    }
}

function Assert-Equal {
    param($Expected, $Actual, [string]$Message)
    if ($Expected -ne $Actual) {
        throw "ASSERT_EQUAL_FAILED: $Message (expected='$Expected' actual='$Actual')"
    }
}

$schema = 'GOAB_API_METADATA_B060_V1'
$apiName = 'apiContrato'
$apiGuid = '11111111-1111-1111-1111-111111111111'
$defaultDescription = 'apiContrato - by Genexus Open API Builder'
$legacyDescription = 'REST API for Contrato, generated by Genexus Open API Builder'
$legacyDescriptionWithPeriod = 'REST API for Contrato, generated by Genexus Open API Builder.'
$editedDescription = 'API REST de Contrato — documentação humana.'

$metadata = [Newtonsoft.Json.Linq.JObject]::Parse(@"
{
  `"schemaVersion`": `"$schema`",
  `"ownership`": {
    `"apiName`": `"$apiName`",
    `"apiGuid`": `"$apiGuid`"
  }
}
"@)

$fallbacks = [string[]]@($defaultDescription, $legacyDescription, $legacyDescriptionWithPeriod)

Assert-True ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::MatchesMetadataOwnership($metadata, $schema, $apiName, $apiGuid)) 'ownership.apiName/apiGuid devem casar.'

$byMetadata = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $true,
    $metadata,
    $schema,
    $apiName,
    $apiGuid,
    $true,
    $true,
    $editedDescription,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::OwnedByMetadata) $byMetadata 'Com metadata, Description editada ainda é própria.'
Assert-True ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::IsOwned($byMetadata)) 'OwnedByMetadata conta como própria.'

$integrityFail = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $true,
    $metadata,
    $schema,
    $apiName,
    $apiGuid,
    $false,
    $true,
    $defaultDescription,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::NotOwned) $integrityFail 'Metadata presente com integridade incompatível não cai no fallback da Description.'

$fallback = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $false,
    $null,
    $schema,
    $apiName,
    $apiGuid,
    $false,
    $true,
    $defaultDescription,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::OwnedByDescriptionFallback) $fallback 'Sem File de metadata, Description padrão permanece fallback.'

$fallbackLegacy = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $false,
    $null,
    $schema,
    $apiName,
    $apiGuid,
    $false,
    $true,
    $legacyDescriptionWithPeriod,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::OwnedByDescriptionFallback) $fallbackLegacy 'Fallback aceita a Description legada com ponto final.'

$fallbackEdited = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $false,
    $null,
    $schema,
    $apiName,
    $apiGuid,
    $false,
    $true,
    $editedDescription,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::NotOwned) $fallbackEdited 'Sem metadata, Description editada perde posse.'

$wrongGuid = [GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership]::Resolve(
    $true,
    $metadata,
    $schema,
    $apiName,
    '22222222-2222-2222-2222-222222222222',
    $true,
    $true,
    $defaultDescription,
    $fallbacks)
Assert-Equal ([GenexusOpenApiBuilder.Extension.Diagnostics.ApiPlanApiObjectOwnership+OwnershipKind]::NotOwned) $wrongGuid 'apiGuid divergente não é própria.'

Write-Output 'PASS: ApiPlanApiObjectOwnership'
