#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;

namespace GenexusOpenApiBuilder.Extension.Diagnostics;

/// <summary>
/// Description canônica de objetos gerados: "{Nome} - by Genexus Open API Builder".
/// Aceita sentinelas legadas (com IDs de backlog ou prosa antiga do API Object) só para reconhecimento.
/// </summary>
public static class ApiPlanOwnedObjectDescription
{
    public const string GeneratorName = "Genexus Open API Builder";
    public const string Suffix = " - by Genexus Open API Builder";

    private const string LegacyProcedurePrefix = "Genexus Open API Builder B050-B053 Procedure";
    private const string LegacySdtPrefix = "Genexus Open API Builder B040-B046 SDT";
    private const string LegacyMetadataPrefix = "Genexus Open API Builder B060 Metadata File";
    private const string LegacyTransactionFolderPrefix = "Genexus Open API Builder Transaction API folder";
    private const string LegacySharedFolderDescription = "Genexus Open API Builder shared SDTs folder";
    private const string LegacyPreferencesDescription = "Genexus Open API Builder Wizard Preferences";

    public static string Create(string objectName)
    {
        if (string.IsNullOrWhiteSpace(objectName))
        {
            throw new ArgumentException("Object name is required.", nameof(objectName));
        }

        return objectName + Suffix;
    }

    public static bool IsCanonical(string? description, string objectName) =>
        string.Equals(description, Create(objectName), StringComparison.Ordinal);

    public static bool IsOwnedProcedure(string? description, string procedureName) =>
        IsCanonical(description, procedureName)
        || StartsWithLegacy(description, LegacyProcedurePrefix);

    public static bool IsOwnedSdt(string? description, string sdtName) =>
        IsCanonical(description, sdtName)
        || StartsWithLegacy(description, LegacySdtPrefix);

    public static bool IsOwnedMetadataFile(string? description, string metadataFileName) =>
        IsCanonical(description, metadataFileName)
        || StartsWithLegacy(description, LegacyMetadataPrefix);

    public static bool IsOwnedSharedFolder(string? description) =>
        IsCanonical(description, "GxOpenAPI")
        || string.Equals(description, LegacySharedFolderDescription, StringComparison.Ordinal);

    public static bool IsOwnedPreferencesFile(string? description) =>
        IsCanonical(description, "GxOpenApiBuilder_Settings")
        || string.Equals(description, LegacyPreferencesDescription, StringComparison.Ordinal);

    public static string CreateTransactionFolderDescription(string folderName) => Create(folderName);

    public static string CreateLegacyTransactionFolderDescription(string transactionName) =>
        $"{LegacyTransactionFolderPrefix} - Transaction={transactionName}";

    /// <summary>
    /// Folder reutilizável: Description humana/vazia, canônica deste Folder, ou sentinela legada desta Transaction.
    /// Sentinela da extensão de outra Transaction (ou nome divergente) bloqueia.
    /// </summary>
    public static bool IsReusableTransactionFolderDescription(
        string? description,
        string folderName,
        string transactionName)
    {
        if (IsCanonical(description, folderName)
            || string.Equals(description, CreateLegacyTransactionFolderDescription(transactionName), StringComparison.Ordinal))
        {
            return true;
        }

        if (StartsWithLegacy(description, LegacyTransactionFolderPrefix))
        {
            return false;
        }

        if (!string.IsNullOrEmpty(description)
            && description!.EndsWith(Suffix, StringComparison.Ordinal)
            && !IsCanonical(description, folderName))
        {
            return false;
        }

        return true;
    }

    public static string CreateApiObjectDescription(string apiName) => Create(apiName);

    public static string CreateLegacyApiObjectDescription(string transactionName, bool withTrailingPeriod = false)
    {
        var value = $"REST API for {transactionName}, generated by {GeneratorName}";
        return withTrailingPeriod ? value + "." : value;
    }

    public static IReadOnlyList<string> CreateApiObjectDescriptionFallbacks(string apiName, string transactionName)
    {
        if (string.IsNullOrWhiteSpace(apiName))
        {
            throw new ArgumentException("API name is required.", nameof(apiName));
        }

        if (string.IsNullOrWhiteSpace(transactionName))
        {
            throw new ArgumentException("Transaction name is required.", nameof(transactionName));
        }

        return new[]
        {
            CreateApiObjectDescription(apiName),
            CreateLegacyApiObjectDescription(transactionName, withTrailingPeriod: false),
            CreateLegacyApiObjectDescription(transactionName, withTrailingPeriod: true),
        }
        .Distinct(StringComparer.Ordinal)
        .ToArray();
    }

    private static bool StartsWithLegacy(string? description, string prefix) =>
        !string.IsNullOrEmpty(description)
        && description!.StartsWith(prefix, StringComparison.Ordinal);
}
